# Form implementation generated from reading ui file 'qtui.ui'
#
# Created by: PyQt6 UI code generator 6.2.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(711, 349)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.read1 = QtWidgets.QPushButton(self.centralwidget)
        self.read1.setGeometry(QtCore.QRect(190, 230, 111, 32))
        self.read1.setObjectName("read1")
        self.getStats = QtWidgets.QPushButton(self.centralwidget)
        self.getStats.setGeometry(QtCore.QRect(420, 230, 113, 32))
        self.getStats.setObjectName("getStats")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 101, 16))
        self.label_2.setObjectName("label_2")
        self.temperatureLimit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.temperatureLimit.setGeometry(QtCore.QRect(10, 40, 51, 31))
        self.temperatureLimit.setObjectName("temperatureLimit")
        self.displayText = QtWidgets.QTextBrowser(self.centralwidget)
        self.displayText.setGeometry(QtCore.QRect(230, 20, 256, 192))
        self.displayText.setObjectName("displayText")
        self.closeProgram = QtWidgets.QPushButton(self.centralwidget)
        self.closeProgram.setGeometry(QtCore.QRect(250, 280, 113, 32))
        self.closeProgram.setObjectName("closeProgram")
        self.humidityLimit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.humidityLimit.setGeometry(QtCore.QRect(10, 110, 41, 31))
        self.humidityLimit.setObjectName("humidityLimit")
        self.read10 = QtWidgets.QPushButton(self.centralwidget)
        self.read10.setGeometry(QtCore.QRect(310, 230, 100, 32))
        self.read10.setObjectName("read10")
        self.Reset = QtWidgets.QPushButton(self.centralwidget)
        self.Reset.setGeometry(QtCore.QRect(380, 280, 100, 32))
        self.Reset.setObjectName("Reset")
        self.Set = QtWidgets.QPushButton(self.centralwidget)
        self.Set.setGeometry(QtCore.QRect(120, 60, 100, 32))
        self.Set.setObjectName("Set")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.read1.setText(_translate("MainWindow", "Read 1 Val"))
        self.getStats.setText(_translate("MainWindow", "Get Stats"))
        self.label.setText(_translate("MainWindow", "Temperature Limit"))
        self.label_2.setText(_translate("MainWindow", "Humidity Limit %"))
        self.temperatureLimit.setPlainText(_translate("MainWindow", "40"))
        self.closeProgram.setText(_translate("MainWindow", "Close"))
        self.humidityLimit.setPlainText(_translate("MainWindow", "80"))
        self.read10.setText(_translate("MainWindow", "Read 10/sec"))
        self.Reset.setText(_translate("MainWindow", "Reset"))
        self.Set.setText(_translate("MainWindow", "Set"))
